/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./components/AuthForm.vue')['default']
    CssPreview: typeof import('./components/CssPreview.vue')['default']
    CssPreviewModal: typeof import('./components/CssPreviewModal.vue')['default']
    CssSettingsModal: typeof import('./components/CssSettingsModal.vue')['default']
    ExportModal: typeof import('./components/ExportModal.vue')['default']
    IconEditDialog: typeof import('./components/IconEditDialog.vue')['default']
    IconGrid: typeof import('./components/IconGrid.vue')['default']
    IconToolbar: typeof import('./components/IconToolbar.vue')['default']
    LibraryList: typeof import('./components/LibraryList.vue')['default']
    OrganizationManager: typeof import('./components/OrganizationManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShikiPreview: typeof import('./components/ShikiPreview.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
  }
}
